language: csharp
solution: bowling-ball.sln
mono: none
dotnet: 2.2.300
install:
    - dotnet restore
script:
    - dotnet build
    - dotnet test BowlingBall.Tests/BowlingBall.Tests.csproj

